package edu.adams.backendboys;

public class AddInjury {
	public static void main(String[] args){
		AthleteTrackerDatabase database = new AthleteTrackerDatabase();
		database.addInjuryType("Head or Face", "Head or Face Abrasion");
		database.addInjuryType("Head or Face", "Concussion");
		database.addInjuryType("Head or Face", "Head or Face Contusion");
		database.addInjuryType("Head or Face", "Orbital Fracture");
		database.addInjuryType("Head or Face", "Nasal Fracture");
		database.addInjuryType("Head or Face", "Zygomatic Arch Fracture");
		database.addInjuryType("Head or Face", "Head or Face Laceration");
		
		database.addInjuryType("Left Ear", "Cauliflower Ear");
		database.addInjuryType("Left Ear", "Ear Infection");
		database.addInjuryType("Right Ear", "Cauliflower Ear");
		database.addInjuryType("Right Ear", "Ear Infection");
		
		
		database.addInjuryType("Left Eye", "Eye Abrasion");
		database.addInjuryType("Left Eye", "Eye Contusion");
		database.addInjuryType("Left Eye", "Eye Dislocation");
		database.addInjuryType("Left Eye", "Eye Infection");
		database.addInjuryType("Left Eye", "Eye Laceration");
		database.addInjuryType("Left Eye", "Eye Miscellaneous");
		
		database.addInjuryType("Right Eye", "Eye Abrasion");
		database.addInjuryType("Right Eye", "Eye Contusion");
		database.addInjuryType("Right Eye", "Eye Dislocation");
		database.addInjuryType("Right Eye", "Eye Infection");
		database.addInjuryType("Right Eye", "Eye Laceration");
		database.addInjuryType("Right Eye", "Eye Miscellaneous");
		
		database.addInjuryType("Cervical Spine or neck", "Exotosis");
		database.addInjuryType("Cervical Spine or neck", "Cervical Spine or neck Fracture");
		database.addInjuryType("Cervical Spine or neck", "Cervical Spine or neck Infection");
		database.addInjuryType("Cervical Spine or neck", "Neurological");
		database.addInjuryType("Cervical Spine or neck", "Cervical Spine or neck Spasm");
		database.addInjuryType("Cervical Spine or neck", "Cervical Spine or neck Strain");
		
		database.addInjuryType("Left Shoulder", "Shoulder Abrasion");
		database.addInjuryType("Left Shoulder", "Subacromial Bursitis");
		database.addInjuryType("Left Shoulder", "Capsulitis");
		database.addInjuryType("Left Shoulder", "Shoulder Contusion");
		database.addInjuryType("Left Shoulder", "Anterior Glenohumoral Dislocation or Subluxation");
		database.addInjuryType("Left Shoulder", "Hill-Sachs Lesion Dislocation or Subluxation");
		database.addInjuryType("Left Shoulder", "Posterior Dislocation Dislocation or Subluxation");
		database.addInjuryType("Left Shoulder", "Sternoclavicular Dislocation or Subluxation");
		database.addInjuryType("Left Shoulder", "Multi-Directional Instability Dislocation or Subluxation");
		database.addInjuryType("Left Shoulder", "Shoulder Impingement");
		database.addInjuryType("Left Shoulder", "Clavicular Fracture");
		database.addInjuryType("Left Shoulder", "Scapular Fracture");
		database.addInjuryType("Left Shoulder", "Glenoid Fossa Fracture");
		database.addInjuryType("Left Shoulder", "Shoulder Infection");
		database.addInjuryType("Left Shoulder", "Acromioclavicular Sprain");
		database.addInjuryType("Left Shoulder", "Sterno-clavicular Sprain");
		database.addInjuryType("Left Shoulder", "Rotator Cuff Strain");
		database.addInjuryType("Left Shoulder", "Deltoid Strain");
		database.addInjuryType("Left Shoulder", "Glenoid Labrum Strain");
		database.addInjuryType("Left Shoulder", "Trapezius Strain");
		database.addInjuryType("Left Shoulder", "Shoulder Synovitis");
		database.addInjuryType("Left Shoulder", "Biceps Tendonitis");
		database.addInjuryType("Left Shoulder", "Rotator Cuff Tendonitis");
		database.addInjuryType("Left Shoulder", "Thoracic Outlet Syndrome");
		
		database.addInjuryType("Right Shoulder", "Shoulder Abrasion");
		database.addInjuryType("Right Shoulder", "Subacromial Bursitis");
		database.addInjuryType("Right Shoulder", "Capsulitis");
		database.addInjuryType("Right Shoulder", "Shoulder Contusion");
		database.addInjuryType("Right Shoulder", "Anterior Glenohumoral Dislocation or Subluxation");
		database.addInjuryType("Right Shoulder", "Hill-Sachs Lesion Dislocation or Subluxation");
		database.addInjuryType("Right Shoulder", "Posterior Dislocation Dislocation or Subluxation");
		database.addInjuryType("Right Shoulder", "Sternoclavicular Dislocation or Subluxation");
		database.addInjuryType("Right Shoulder", "Multi-Directional Instability Dislocation or Subluxation");
		database.addInjuryType("Right Shoulder", "Shoulder Impingement");
		database.addInjuryType("Right Shoulder", "Clavicular Fracture");
		database.addInjuryType("Right Shoulder", "Scapular Fracture");
		database.addInjuryType("Right Shoulder", "Glenoid Fossa Fracture");
		database.addInjuryType("Right Shoulder", "Shoulder Infection");
		database.addInjuryType("Right Shoulder", "Acromioclavicular Sprain");
		database.addInjuryType("Right Shoulder", "Sterno-clavicular Sprain");
		database.addInjuryType("Right Shoulder", "Rotator Cuff Strain");
		database.addInjuryType("Right Shoulder", "Deltoid Strain");
		database.addInjuryType("Right Shoulder", "Glenoid Labrum Strain");
		database.addInjuryType("Right Shoulder", "Trapezius Strain");
		database.addInjuryType("Right Shoulder", "Shoulder Synovitis");
		database.addInjuryType("Right Shoulder", "Biceps Tendonitis");
		database.addInjuryType("Right Shoulder", "Rotator Cuff Tendonitis");
		database.addInjuryType("Right Shoulder", "Thoracic Outlet Syndrome");
		
		database.addInjuryType("Left Upper Arm", "Upper Arm Abrasion");
		database.addInjuryType("Left Upper Arm", "Upper Arm Contusion");
		database.addInjuryType("Left Upper Arm", "Upper Arm Fracture");
		database.addInjuryType("Left Upper Arm", "Upper Arm Infection");
		database.addInjuryType("Left Upper Arm", "Myositis Ossificans");
		database.addInjuryType("Left Upper Arm", "Upper Arm Spasm");
		database.addInjuryType("Left Upper Arm", "Biceps or Brachialis or Brachioradialis Strain or Tear");
		database.addInjuryType("Left Upper Arm", "Triceps Strain or Tear");
		database.addInjuryType("Left Upper Arm", "Biceps Tendonitis");
		database.addInjuryType("Left Upper Arm", "Triceps Tendonitis");
		
		database.addInjuryType("Right Upper Arm", "Upper Arm Abrasion");
		database.addInjuryType("Right Upper Arm", "Upper Arm Contusion");
		database.addInjuryType("Right Upper Arm", "Upper Arm Fracture");
		database.addInjuryType("Right Upper Arm", "Upper Arm Infection");
		database.addInjuryType("Right Upper Arm", "Myositis Ossificans");
		database.addInjuryType("Right Upper Arm", "Upper Arm Spasm");
		database.addInjuryType("Right Upper Arm", "Biceps or Brachialis or Brachioradialis Strain or Tear");
		database.addInjuryType("Right Upper Arm", "Triceps Strain or Tear");
		database.addInjuryType("Right Upper Arm", "Biceps Tendonitis");
		database.addInjuryType("Right Upper Arm", "Triceps Tendonitis");
		
		
		
		database.addInjuryType("Left Elbow", "Elbow Abrasion");
		database.addInjuryType("Left Elbow", "Elbow Bursitis");
		database.addInjuryType("Left Elbow", "Elbow Contusion");
		database.addInjuryType("Left Elbow", "Elbow Dislocation or Subluxation");
		database.addInjuryType("Left Elbow", "Elbow Fracture");
		database.addInjuryType("Left Elbow", "Elbow Impingement");
		database.addInjuryType("Left Elbow", "Elbow Infection");
		database.addInjuryType("Left Elbow", "Elbow Inflammation");
		database.addInjuryType("Left Elbow", "Osteochondritis");
		database.addInjuryType("Left Elbow", "Annular Ligament Sprain");
		database.addInjuryType("Left Elbow", "Capsular Sprain");
		database.addInjuryType("Left Elbow", "Ulnar Collateral Ligament Sprain");
		database.addInjuryType("Left Elbow", "Hyperextention Strain or Tear");

		database.addInjuryType("Right Elbow", "Elbow Abrasion");
		database.addInjuryType("Right Elbow", "Elbow Bursitis");
		database.addInjuryType("Right Elbow", "Elbow Contusion");
		database.addInjuryType("Right Elbow", "Elbow Dislocation or Subluxation");
		database.addInjuryType("Right Elbow", "Elbow Fracture");
		database.addInjuryType("Right Elbow", "Elbow Impingement");
		database.addInjuryType("Right Elbow", "Elbow Infection");
		database.addInjuryType("Right Elbow", "Elbow Inflammation");
		database.addInjuryType("Right Elbow", "Osteochondritis");
		database.addInjuryType("Right Elbow", "Annular Ligament Sprain");
		database.addInjuryType("Right Elbow", "Capsular Sprain");
		database.addInjuryType("Right Elbow", "Ulnar Collateral Ligament Sprain");
		database.addInjuryType("Right Elbow", "Hyperextention Strain or Tear");
		
		database.addInjuryType("Left Forearm", "Forearm Abrasion");
		database.addInjuryType("Left Forearm", "Compartment Syndrome");
		database.addInjuryType("Left Forearm", "Forearm Contusion");
		database.addInjuryType("Left Forearm", "Ulna Fracture");
		database.addInjuryType("Left Forearm", "Radius Fracture");
		database.addInjuryType("Left Forearm", "Flexors Spasm");
		database.addInjuryType("Left Forearm", "Extensors Spasm");
		database.addInjuryType("Left Forearm", "Flexors Strain");
		database.addInjuryType("Left Forearm", "Extensors Strain");
		
		database.addInjuryType("Right Forearm", "Forearm Abrasion");
		database.addInjuryType("Right Forearm", "Compartment Syndrome");
		database.addInjuryType("Right Forearm", "Forearm Contusion");
		database.addInjuryType("Right Forearm", "Ulna Fracture");
		database.addInjuryType("Right Forearm", "Radius Fracture");
		database.addInjuryType("Right Forearm", "Flexors Spasm");
		database.addInjuryType("Right Forearm", "Extensors Spasm");
		database.addInjuryType("Right Forearm", "Flexors Strain");
		database.addInjuryType("Right Forearm", "Extensors Strain");

		
		database.addInjuryType("Left Wrist", "Scaphoid Avascular Necrosis");
		database.addInjuryType("Left Wrist", "Capulitis");
		database.addInjuryType("Left Wrist", "Wrist Contusion");
		database.addInjuryType("Left Wrist", "Distal Radio-Ulnar Joint Dislocation or Subluxation");
		database.addInjuryType("Left Wrist", "Scapholunate Dislocation or Subluxation");
		database.addInjuryType("Left Wrist", "Ulnar Nerve Entrapment (Tunnel of Guyon) Impingement");
		database.addInjuryType("Left Wrist", "Wrist Scaphoid Fracture");
		database.addInjuryType("Left Wrist", "Wrist Carpal (minus Scaphoid) Fracture");
		database.addInjuryType("Left Wrist", "Wrist Infection");
		database.addInjuryType("Left Wrist", "Carpal Tunnel Syndrome Neurological");
		database.addInjuryType("Left Wrist", "Dorsal Wrist Ganglion Neurological");
		database.addInjuryType("Left Wrist", "Volar Wrist Ganglion Neurological");
		database.addInjuryType("Left Wrist", "Wrist Neuroma Neurological");
		database.addInjuryType("Left Wrist", "Wrist Sprain");
		database.addInjuryType("Left Wrist", "Hyperextension Strain");
		database.addInjuryType("Left Wrist", "Triangular Fibrocartilage Complex Strain");
		database.addInjuryType("Left Wrist", "Extensor Tendon Strain");
		database.addInjuryType("Left Wrist", "Flexor Tendon Strain");
		database.addInjuryType("Left Wrist", "Extensor Tenosynovitis");
		database.addInjuryType("Left Wrist", "Flexor Tenosynovitis");
		
		database.addInjuryType("Right Wrist", "Scaphoid Avascular Necrosis");
		database.addInjuryType("Right Wrist", "Capulitis");
		database.addInjuryType("Right Wrist", "Wrist Contusion");
		database.addInjuryType("Right Wrist", "Distal Radio-Ulnar Joint Dislocation or Subluxation");
		database.addInjuryType("Right Wrist", "Scapholunate Dislocation or Subluxation");
		database.addInjuryType("Right Wrist", "Ulnar Nerve Entrapment (Tunnel of Guyon) Impingement");
		database.addInjuryType("Right Wrist", "Wrist Scaphoid Fracture");
		database.addInjuryType("Right Wrist", "Wrist Carpal (minus Scaphoid) Fracture");
		database.addInjuryType("Right Wrist", "Wrist Infection");
		database.addInjuryType("Right Wrist", "Carpal Tunnel Syndrome Neurological");
		database.addInjuryType("Right Wrist", "Dorsal Wrist Ganglion Neurological");
		database.addInjuryType("Right Wrist", "Volar Wrist Ganglion Neurological");
		database.addInjuryType("Right Wrist", "Wrist Neuroma Neurological");
		database.addInjuryType("Right Wrist", "Wrist Sprain");
		database.addInjuryType("Right Wrist", "Hyperextension Strain");
		database.addInjuryType("Right Wrist", "Triangular Fibrocartilage Complex Strain");
		database.addInjuryType("Right Wrist", "Extensor Tendon Strain");
		database.addInjuryType("Right Wrist", "Flexor Tendon Strain");
		database.addInjuryType("Right Wrist", "Extensor Tenosynovitis");
		database.addInjuryType("Right Wrist", "Flexor Tenosynovitis");
		
		database.addInjuryType("Left Hand or Fingers", "Hand or Fingers Abrasion");
		database.addInjuryType("Left Hand or Fingers", "Hand or Fingers Contusion");
		database.addInjuryType("Left Hand or Fingers", "PIP or DIP Joint Dislocation");
		database.addInjuryType("Left Hand or Fingers", "Interphalangeal Joint (1st) Dislocation");
		database.addInjuryType("Left Hand or Fingers", "MCP Joint (1st) Dislocation");
		database.addInjuryType("Left Hand or Fingers", "MCP Joint (2-5) Dislocation");
		database.addInjuryType("Left Hand or Fingers", "Metacarpal (1st) Fracture");
		database.addInjuryType("Left Hand or Fingers", "Metacarpal (2-5) Fracture");
		database.addInjuryType("Left Hand or Fingers", "Phalangeal Fracture");
		database.addInjuryType("Left Hand or Fingers", "Phalnyx Fracture");
		database.addInjuryType("Left Hand or Fingers", "Hand or Fingers Infection");
		database.addInjuryType("Left Hand or Fingers", "Hand or Fingers Inflammation");
		database.addInjuryType("Left Hand or Fingers", "DIP Joint (2-5) Sprain");
		database.addInjuryType("Left Hand or Fingers", "IP Joint (1st) Sprain");
		database.addInjuryType("Left Hand or Fingers", "MCP Joint Sprain");
		database.addInjuryType("Left Hand or Fingers", "PIP Joint Sprain");
		database.addInjuryType("Left Hand or Fingers", "Radial Collateral Ligament (1st) Sprain");
		database.addInjuryType("Left Hand or Fingers", "Ulnar Collateral Ligament (Gamekeepers) Sprain");
		database.addInjuryType("Left Hand or Fingers", "Flexors Strain or Tear");
		database.addInjuryType("Left Hand or Fingers", "Extensors Strain or Tear");
		
		database.addInjuryType("Right Hand or Fingers", "Hand or Fingers Abrasion");
		database.addInjuryType("Right Hand or Fingers", "Hand or Fingers Contusion");
		database.addInjuryType("Right Hand or Fingers", "PIP or DIP Joint Dislocation");
		database.addInjuryType("Right Hand or Fingers", "Interphalangeal Joint (1st) Dislocation");
		database.addInjuryType("Right Hand or Fingers", "MCP Joint (1st) Dislocation");
		database.addInjuryType("Right Hand or Fingers", "MCP Joint (2-5) Dislocation");
		database.addInjuryType("Right Hand or Fingers", "Metacarpal (1st) Fracture");
		database.addInjuryType("Right Hand or Fingers", "Metacarpal (2-5) Fracture");
		database.addInjuryType("Right Hand or Fingers", "Phalangeal Fracture");
		database.addInjuryType("Right Hand or Fingers", "Phalnyx Fracture");
		database.addInjuryType("Right Hand or Fingers", "Hand or Fingers Infection");
		database.addInjuryType("Right Hand or Fingers", "Hand or Fingers Inflammation");
		database.addInjuryType("Right Hand or Fingers", "DIP Joint (2-5) Sprain");
		database.addInjuryType("Right Hand or Fingers", "IP Joint (1st) Sprain");
		database.addInjuryType("Right Hand or Fingers", "MCP Joint Sprain");
		database.addInjuryType("Right Hand or Fingers", "PIP Joint Sprain");
		database.addInjuryType("Right Hand or Fingers", "Radial Collateral Ligament (1st) Sprain");
		database.addInjuryType("Right Hand or Fingers", "Ulnar Collateral Ligament (Gamekeepers) Sprain");
		database.addInjuryType("Right Hand or Fingers", "Flexors Strain or Tear");
		database.addInjuryType("Right Hand or Fingers", "Extensors Strain or Tear");
		
		database.addInjuryType("Chest or Ribs", "Chest or Ribs Contusion");
		database.addInjuryType("Chest or Ribs", "Chest or Ribs Fracture");
		database.addInjuryType("Chest or Ribs", "Chest or Ribs Infection");
		database.addInjuryType("Chest or Ribs", "Chest or Ribs Spasm");
		database.addInjuryType("Chest or Ribs", "Chest or Ribs Strain or Tear");
		database.addInjuryType("Chest or Ribs", "Chest or Ribs Subluxation");
		
		database.addInjuryType("Thoracic Spine", "Thoracic Spine Contusion");
		database.addInjuryType("Thoracic Spine", "Thoracic Spine Fracture");
		database.addInjuryType("Thoracic Spine", "Paraspinal Spasm");
		database.addInjuryType("Thoracic Spine", "Rhomboid Spasm");
		database.addInjuryType("Thoracic Spine", "Trapezius Spasm");
		database.addInjuryType("Thoracic Spine", "Facet Joint Sprain");
		database.addInjuryType("Thoracic Spine", "Interspinous Ligament Sprain");
		database.addInjuryType("Thoracic Spine", "Rhomboid Strain");
		database.addInjuryType("Thoracic Spine", "Serratus Anterior Strain");
		
		database.addInjuryType("Abdomen", "Abdomen Strain or tear");
		database.addInjuryType("Abdomen", "Abdomen Spasm");
		database.addInjuryType("Abdomen", "Abdomen Contusion");
		database.addInjuryType("Abdomen", "Abdomen Infection");
		database.addInjuryType("Abdomen", "Internal Organ");
		
		database.addInjuryType("Lumbar Spine", "Lumbar Spine Contusion");
		database.addInjuryType("Lumbar Spine", "Sponylolysis Fracture");
		database.addInjuryType("Lumbar Spine", "Pars Fracture");
		database.addInjuryType("Lumbar Spine", "Sciatica");
		database.addInjuryType("Lumbar Spine", "Lumbar Spine Spasm");
		database.addInjuryType("Lumbar Spine", "Facet Joint Sprain");
		database.addInjuryType("Lumbar Spine", "Lumbar Spine Strain");
		
		database.addInjuryType("Left Hip or Groin", "Hip or Groin Abrasion");
		database.addInjuryType("Left Hip or Groin", "Hip or Groin Bursitis");
		database.addInjuryType("Left Hip or Groin", "Cartilage Injury");
		database.addInjuryType("Left Hip or Groin", "Hip or Groin Contusion");
		database.addInjuryType("Left Hip or Groin", "Hip or Groin Dislocation");
		database.addInjuryType("Left Hip or Groin", "Hip or Groin Fracture");
		database.addInjuryType("Left Hip or Groin", "Hip or Groin Impingement");
		database.addInjuryType("Left Hip or Groin", "Hip or Groin Infection");
		database.addInjuryType("Left Hip or Groin", "Hip or Groin Inflammation");
		database.addInjuryType("Left Hip or Groin", "Adductor Spasm");
		database.addInjuryType("Left Hip or Groin", "Glute Spasm");
		database.addInjuryType("Left Hip or Groin", "Abductors Strain or Tear");
		database.addInjuryType("Left Hip or Groin", "Adductors Strain or Tear");
		database.addInjuryType("Left Hip or Groin", "Piriformis Strain or Tear");
		database.addInjuryType("Left Hip or Groin", "Hip Flexor Strain or Tear");
		database.addInjuryType("Left Hip or Groin", "Iliopsoas or Sartorius Strain or Tear");
		database.addInjuryType("Left Hip or Groin", "Internal Rotators Strain or Tear");
		
		database.addInjuryType("Right Hip or Groin", "Hip or Groin Abrasion");
		database.addInjuryType("Right Hip or Groin", "Hip or Groin Bursitis");
		database.addInjuryType("Right Hip or Groin", "Cartilage Injury");
		database.addInjuryType("Right Hip or Groin", "Hip or Groin Contusion");
		database.addInjuryType("Right Hip or Groin", "Hip or Groin Dislocation");
		database.addInjuryType("Right Hip or Groin", "Hip or Groin Fracture");
		database.addInjuryType("Right Hip or Groin", "Hip or Groin Impingement");
		database.addInjuryType("Right Hip or Groin", "Hip or Groin Infection");
		database.addInjuryType("Right Hip or Groin", "Hip or Groin Inflammation");
		database.addInjuryType("Right Hip or Groin", "Adductor Spasm");
		database.addInjuryType("Right Hip or Groin", "Glute Spasm");
		database.addInjuryType("Right Hip or Groin", "Abductors Strain or Tear");
		database.addInjuryType("Right Hip or Groin", "Adductors Strain or Tear");
		database.addInjuryType("Right Hip or Groin", "Piriformis Strain or Tear");
		database.addInjuryType("Right Hip or Groin", "Hip Flexor Strain or Tear");
		database.addInjuryType("Right Hip or Groin", "Iliopsoas or Sartorius Strain or Tear");
		database.addInjuryType("Right Hip or Groin", "Internal Rotators Strain or Tear");
		
		database.addInjuryType("Sacrum or Pelvis", "Sacrum or Pelvis Contusion");
		database.addInjuryType("Sacrum or Pelvis", "Illium Fracture");
		database.addInjuryType("Sacrum or Pelvis", "Ischium Fracture");
		database.addInjuryType("Sacrum or Pelvis", "Pubis Fracture");
		database.addInjuryType("Sacrum or Pelvis", "Sacral or Coccyx Fracture");
		database.addInjuryType("Sacrum or Pelvis", "Pubic Symphysis Sprain");
		
		database.addInjuryType("Left Thigh", "Thigh Abrasion");
		database.addInjuryType("Left Thigh", "Thigh Contusion");
		database.addInjuryType("Left Thigh", "Femor Fracture");
		database.addInjuryType("Left Thigh", "Femoral Neck Fracture");
		database.addInjuryType("Left Thigh", "Myositis Ossificans");
		database.addInjuryType("Left Thigh", "Hamstring Spasm");
		database.addInjuryType("Left Thigh", "Quadriceps Spasm");
		database.addInjuryType("Left Thigh", "Tensor Fasciae Latae Spasm");
		database.addInjuryType("Left Thigh", "Hamstring Strain");
		database.addInjuryType("Left Thigh", "Illiotibial Band Strain");
		database.addInjuryType("Left Thigh", "Quadriceps Strain");
		database.addInjuryType("Left Thigh", "Quadriceps Tendon Strain");
		database.addInjuryType("Left Thigh", "Tensor Fasciae Latae Strain");
		database.addInjuryType("Left Thigh", "Hamstring Tendonitis");
		database.addInjuryType("Left Thigh", "Quadriceps Tendonitis");
		
		database.addInjuryType("Right Thigh", "Thigh Abrasion");
		database.addInjuryType("Right Thigh", "Thigh Contusion");
		database.addInjuryType("Right Thigh", "Femor Fracture");
		database.addInjuryType("Right Thigh", "Femoral Neck Fracture");
		database.addInjuryType("Right Thigh", "Myositis Ossificans");
		database.addInjuryType("Right Thigh", "Hamstring Spasm");
		database.addInjuryType("Right Thigh", "Quadriceps Spasm");
		database.addInjuryType("Right Thigh", "Tensor Fasciae Latae Spasm");
		database.addInjuryType("Right Thigh", "Hamstring Strain");
		database.addInjuryType("Right Thigh", "Illiotibial Band Strain");
		database.addInjuryType("Right Thigh", "Quadriceps Strain");
		database.addInjuryType("Right Thigh", "Quadriceps Tendon Strain");
		database.addInjuryType("Right Thigh", "Tensor Fasciae Latae Strain");
		database.addInjuryType("Right Thigh", "Hamstring Tendonitis");
		database.addInjuryType("Right Thigh", "Quadriceps Tendonitis");
		
		database.addInjuryType("Right Knee", "Knee Abrasion");
		database.addInjuryType("Right Knee", "Infrapatellar Bursitis");
		database.addInjuryType("Right Knee", "Medial Collateral Bursitis");
		database.addInjuryType("Right Knee", "Pes Anserine Bursitis");
		database.addInjuryType("Right Knee", "Prepatellar Bursitis");
		database.addInjuryType("Right Knee", "Capsulitis");
		database.addInjuryType("Right Knee", "Lateral Meniscus Cartilage Injury");
		database.addInjuryType("Right Knee", "Medial Meniscus Cartilage Injury");
		database.addInjuryType("Right Knee", "Contusion");
		database.addInjuryType("Right Knee", "Patellar Dislocation or Subluxation");
		database.addInjuryType("Right Knee", "Knee Dislocation or Subluxation");
		database.addInjuryType("Right Knee", "Proximal Tibio-Fibular Dislocation or Subluxation");
		database.addInjuryType("Right Knee", "Femoral Condyle Fracture");
		database.addInjuryType("Right Knee", "Fibular Head Fracture");
		database.addInjuryType("Right Knee", "Patella Fracture");
		database.addInjuryType("Right Knee", "Tibial Plateau Fracture");
		database.addInjuryType("Right Knee", "Knee Infection");
		database.addInjuryType("Right Knee", "IT Band Friction Syndrome Inflammation");
		database.addInjuryType("Right Knee", "Plica Syndrome Inflammation");
		database.addInjuryType("Right Knee", "Osteochondritis");
		database.addInjuryType("Right Knee", "Anterior Cruciate Ligament Sprain");
		database.addInjuryType("Right Knee", "Capsular Sprain");
		database.addInjuryType("Right Knee", "Lateral Collateral Ligament Sprain");
		database.addInjuryType("Right Knee", "Lateral Retinaculum Sprain");
		database.addInjuryType("Right Knee", "Medial Collateral Ligament Sprain");
		database.addInjuryType("Right Knee", "Medical Retinaculum Sprain");
		database.addInjuryType("Right Knee", "Posterior Cruciate Ligament Sprain");
		database.addInjuryType("Right Knee", "Patellar Tendon Strain");
		database.addInjuryType("Right Knee", "Knee Synovitis");
		database.addInjuryType("Right Knee", "Patellar Tendonitis");
		database.addInjuryType("Right Knee", "Pes Anserine Tendonitis");
		database.addInjuryType("Right Knee", "Popliteus Tendonitis");
		
		database.addInjuryType("Left Knee", "Knee Abrasion");
		database.addInjuryType("Left Knee", "Infrapatellar Bursitis");
		database.addInjuryType("Left Knee", "Medial Collateral Bursitis");
		database.addInjuryType("Left Knee", "Pes Anserine Bursitis");
		database.addInjuryType("Left Knee", "Prepatellar Bursitis");
		database.addInjuryType("Left Knee", "Capsulitis");
		database.addInjuryType("Left Knee", "Lateral Meniscus Cartilage Injury");
		database.addInjuryType("Left Knee", "Medial Meniscus Cartilage Injury");
		database.addInjuryType("Left Knee", "Contusion");
		database.addInjuryType("Left Knee", "Patellar Dislocation or Subluxation");
		database.addInjuryType("Left Knee", "Knee Dislocation or Subluxation");
		database.addInjuryType("Left Knee", "Proximal Tibio-Fibular Dislocation or Subluxation");
		database.addInjuryType("Left Knee", "Femoral Condyle Fracture");
		database.addInjuryType("Left Knee", "Fibular Head Fracture");
		database.addInjuryType("Left Knee", "Patella Fracture");
		database.addInjuryType("Left Knee", "Tibial Plateau Fracture");
		database.addInjuryType("Left Knee", "Knee Infection");
		database.addInjuryType("Left Knee", "IT Band Friction Syndrome Inflammation");
		database.addInjuryType("Left Knee", "Plica Syndrome Inflammation");
		database.addInjuryType("Left Knee", "Osteochondritis");
		database.addInjuryType("Left Knee", "Anterior Cruciate Ligament Sprain");
		database.addInjuryType("Left Knee", "Capsular Sprain");
		database.addInjuryType("Left Knee", "Lateral Collateral Ligament Sprain");
		database.addInjuryType("Left Knee", "Lateral Retinaculum Sprain");
		database.addInjuryType("Left Knee", "Medial Collateral Ligament Sprain");
		database.addInjuryType("Left Knee", "Medical Retinaculum Sprain");
		database.addInjuryType("Left Knee", "Posterior Cruciate Ligament Sprain");
		database.addInjuryType("Left Knee", "Patellar Tendon Strain");
		database.addInjuryType("Left Knee", "Knee Synovitis");
		database.addInjuryType("Left Knee", "Patellar Tendonitis");
		database.addInjuryType("Left Knee", "Pes Anserine Tendonitis");
		database.addInjuryType("Left Knee", "Popliteus Tendonitis");
		
		database.addInjuryType("Left Lower Leg", "Lower Leg Abrasion");
		database.addInjuryType("Left Lower Leg", "Achilles Bursitis");
		database.addInjuryType("Left Lower Leg", "Anterior Compartment Syndrome");
		database.addInjuryType("Left Lower Leg", "Deep Posterior Compartment Syndrome");
		database.addInjuryType("Left Lower Leg", "Lateral Compartment Syndrome");
		database.addInjuryType("Left Lower Leg", "Posterior Compartment Syndrome");
		database.addInjuryType("Left Lower Leg", "Lower Leg Contusion");
		database.addInjuryType("Left Lower Leg", "Fibular Fracture");
		database.addInjuryType("Left Lower Leg", "Tibial Fracture");
		database.addInjuryType("Left Lower Leg", "Anterior Tibial Stress Syndrome Inflammation");
		database.addInjuryType("Left Lower Leg", "Medial Tibial Stress Syndrome Inflammation");
		database.addInjuryType("Left Lower Leg", "Dorsi-Flexors Spasm");
		database.addInjuryType("Left Lower Leg", "Everters Spasm");
		database.addInjuryType("Left Lower Leg", "Inverters Spasm");
		database.addInjuryType("Left Lower Leg", "Plantar Flexors Spasm");
		database.addInjuryType("Left Lower Leg", "Achilles Tendon Strain");
		database.addInjuryType("Left Lower Leg", "Gastrocnemius Strain");
		database.addInjuryType("Left Lower Leg", "Peroneals Strain");
		database.addInjuryType("Left Lower Leg", "Soleus Strain");
		database.addInjuryType("Left Lower Leg", "Tibialis Anterior Strain");
		database.addInjuryType("Left Lower Leg", "Tibialis Posterior Strain");
		database.addInjuryType("Left Lower Leg", "Achilles Tendonitis");
		database.addInjuryType("Left Lower Leg", "Peroneal Tendonitis");
		database.addInjuryType("Left Lower Leg", "Tibialis Anterior Tendonitis");
		database.addInjuryType("Left Lower Leg", "Tibialis Posterior Tendonitis");
		
		database.addInjuryType("Right Lower Leg", "Lower Leg Abrasion");
		database.addInjuryType("Right Lower Leg", "Achilles Bursitis");
		database.addInjuryType("Right Lower Leg", "Anterior Compartment Syndrome");
		database.addInjuryType("Right Lower Leg", "Deep Posterior Compartment Syndrome");
		database.addInjuryType("Right Lower Leg", "Lateral Compartment Syndrome");
		database.addInjuryType("Right Lower Leg", "Posterior Compartment Syndrome");
		database.addInjuryType("Right Lower Leg", "Lower Leg Contusion");
		database.addInjuryType("Right Lower Leg", "Fibular Fracture");
		database.addInjuryType("Right Lower Leg", "Tibial Fracture");
		database.addInjuryType("Right Lower Leg", "Anterior Tibial Stress Syndrome Inflammation");
		database.addInjuryType("Right Lower Leg", "Medial Tibial Stress Syndrome Inflammation");
		database.addInjuryType("Right Lower Leg", "Dorsi-Flexors Spasm");
		database.addInjuryType("Right Lower Leg", "Everters Spasm");
		database.addInjuryType("Right Lower Leg", "Inverters Spasm");
		database.addInjuryType("Right Lower Leg", "Plantar Flexors Spasm");
		database.addInjuryType("Right Lower Leg", "Achilles Tendon Strain");
		database.addInjuryType("Right Lower Leg", "Gastrocnemius Strain");
		database.addInjuryType("Right Lower Leg", "Peroneals Strain");
		database.addInjuryType("Right Lower Leg", "Soleus Strain");
		database.addInjuryType("Right Lower Leg", "Tibialis Anterior Strain");
		database.addInjuryType("Right Lower Leg", "Tibialis Posterior Strain");
		database.addInjuryType("Right Lower Leg", "Achilles Tendonitis");
		database.addInjuryType("Right Lower Leg", "Peroneal Tendonitis");
		database.addInjuryType("Right Lower Leg", "Tibialis Anterior Tendonitis");
		database.addInjuryType("Right Lower Leg", "Tibialis Posterior Tendonitis");
		
		database.addInjuryType("Left Ankle", "Ankle Abrasion");
		database.addInjuryType("Left Ankle", "Ankle Bursitis");
		database.addInjuryType("Left Ankle", "Ankle Cartilage");
		database.addInjuryType("Left Ankle", "Ankle Dislocation");
		database.addInjuryType("Left Ankle", "Ankle Fracture");
		database.addInjuryType("Left Ankle", "Ankle Infection");
		database.addInjuryType("Left Ankle", "Ankle Inflammation");
		database.addInjuryType("Left Ankle", "Tibiofibular Syndesmosis Sprain");
		database.addInjuryType("Left Ankle", "Capsular Sprain");
		database.addInjuryType("Left Ankle", "Lateral Sprain");
		database.addInjuryType("Left Ankle", "Medial Sprain");
		database.addInjuryType("Left Ankle", "Ankle Synovitis");
		
		database.addInjuryType("Right Ankle", "Ankle Abrasion");
		database.addInjuryType("Right Ankle", "Ankle Bursitis");
		database.addInjuryType("Right Ankle", "Ankle Cartilage");
		database.addInjuryType("Right Ankle", "Ankle Dislocation");
		database.addInjuryType("Right Ankle", "Ankle Fracture");
		database.addInjuryType("Right Ankle", "Ankle Infection");
		database.addInjuryType("Right Ankle", "Ankle Inflammation");
		database.addInjuryType("Right Ankle", "Tibiofibular Syndesmosis Sprain");
		database.addInjuryType("Right Ankle", "Capsular Sprain");
		database.addInjuryType("Right Ankle", "Lateral Sprain");
		database.addInjuryType("Right Ankle", "Medial Sprain");
		database.addInjuryType("Right Ankle", "Ankle Synovitis");
		
		database.addInjuryType("Left Foot or Toes", "Foot or Toes Abrasion");
		database.addInjuryType("Left Foot or Toes", "Foot or Toes Bursitis");
		database.addInjuryType("Left Foot or Toes", "Foot or Toes Contusion");
		database.addInjuryType("Left Foot or Toes", "Cuboid Dislocation or Subluxation");
		database.addInjuryType("Left Foot or Toes", "MTP Joint (1st) Dislocation or Subluxation");
		database.addInjuryType("Left Foot or Toes", "MTP Joint (2-5) Dislocation or Subluxation");
		database.addInjuryType("Left Foot or Toes", "Lisfranc Dislocation or Subluxation");
		database.addInjuryType("Left Foot or Toes", "Subtalar Dislocation or Subluxation");
		database.addInjuryType("Left Foot or Toes", "Calcaneal Fracture");
		database.addInjuryType("Left Foot or Toes", "Cuboid Fracture");
		database.addInjuryType("Left Foot or Toes", "Cuneiform Fracture");
		database.addInjuryType("Left Foot or Toes", "Metatarsal (1st) Fracture");
		database.addInjuryType("Left Foot or Toes", "Metatarsal (2-4) Fracture");
		database.addInjuryType("Left Foot or Toes", "Metatarsal (5th) Fracture");
		database.addInjuryType("Left Foot or Toes", "Lisfranc Fracture");
		database.addInjuryType("Left Foot or Toes", "Navicular Fracture");
		database.addInjuryType("Left Foot or Toes", "Foot or Toes Infection");
		database.addInjuryType("Left Foot or Toes", "Foot or Toes Inflammation");
		database.addInjuryType("Left Foot or Toes", "Foot or Toes Spasm");
		database.addInjuryType("Left Foot or Toes", "Medial Arch Sprain");
		database.addInjuryType("Left Foot or Toes", "Metatarsal Arch Sprain");
		database.addInjuryType("Left Foot or Toes", "Midfoot Sprain");
		database.addInjuryType("Left Foot or Toes", "Spring Ligament Sprain");
		database.addInjuryType("Left Foot or Toes", "Turf Toe Sprain");
		database.addInjuryType("Left Foot or Toes", "Achilles Tendon Strain or Tear");
		database.addInjuryType("Left Foot or Toes", "Central Slip Tear Strain or Tear");
		database.addInjuryType("Left Foot or Toes", "Forefoot Extensors Strain or Tear");
		database.addInjuryType("Left Foot or Toes", "Forefoot Flexors Strain or Tear");
		database.addInjuryType("Left Foot or Toes", "Plantar Fascia Strain or Tear");
		
		database.addInjuryType("Right Foot or Toes", "Foot or Toes Abrasion");
		database.addInjuryType("Right Foot or Toes", "Foot or Toes Bursitis");
		database.addInjuryType("Right Foot or Toes", "Foot or Toes Contusion");
		database.addInjuryType("Right Foot or Toes", "Cuboid Dislocation or Subluxation");
		database.addInjuryType("Right Foot or Toes", "MTP Joint (1st) Dislocation or Subluxation");
		database.addInjuryType("Right Foot or Toes", "MTP Joint (2-5) Dislocation or Subluxation");
		database.addInjuryType("Right Foot or Toes", "Lisfranc Dislocation or Subluxation");
		database.addInjuryType("Right Foot or Toes", "Subtalar Dislocation or Subluxation");
		database.addInjuryType("Right Foot or Toes", "Calcaneal Fracture");
		database.addInjuryType("Right Foot or Toes", "Cuboid Fracture");
		database.addInjuryType("Right Foot or Toes", "Cuneiform Fracture");
		database.addInjuryType("Right Foot or Toes", "Metatarsal (1st) Fracture");
		database.addInjuryType("Right Foot or Toes", "Metatarsal (2-4) Fracture");
		database.addInjuryType("Right Foot or Toes", "Metatarsal (5th) Fracture");
		database.addInjuryType("Right Foot or Toes", "Lisfranc Fracture");
		database.addInjuryType("Right Foot or Toes", "Navicular Fracture");
		database.addInjuryType("Right Foot or Toes", "Foot or Toes Infection");
		database.addInjuryType("Right Foot or Toes", "Foot or Toes Inflammation");
		database.addInjuryType("Right Foot or Toes", "Foot or Toes Spasm");
		database.addInjuryType("Right Foot or Toes", "Medial Arch Sprain");
		database.addInjuryType("Right Foot or Toes", "Metatarsal Arch Sprain");
		database.addInjuryType("Right Foot or Toes", "Midfoot Sprain");
		database.addInjuryType("Right Foot or Toes", "Spring Ligament Sprain");
		database.addInjuryType("Right Foot or Toes", "Turf Toe Sprain");
		database.addInjuryType("Right Foot or Toes", "Achilles Tendon Strain or Tear");
		database.addInjuryType("Right Foot or Toes", "Central Slip Tear Strain or Tear");
		database.addInjuryType("Right Foot or Toes", "Forefoot Extensors Strain or Tear");
		database.addInjuryType("Right Foot or Toes", "Forefoot Flexors Strain or Tear");
		database.addInjuryType("Right Foot or Toes", "Plantar Fascia Strain or Tear");
		
		database.addInjuryType("Cardiovascular", "Cardiovascular Infection");
		database.addInjuryType("Cardiovascular", "Cardiovascular Miscellaneous");
		
		database.addInjuryType("Illness", "Upper Respiratory (Cold)");
		database.addInjuryType("Illness", "Influenza");
		database.addInjuryType("Illness", "Pharyngitis");
		database.addInjuryType("Illness", "Pnuemonia");
		database.addInjuryType("Illness", "Tonsilitis");
		
		// database.addInjuryType("Infection-Internal", "");
		
		 for(String injuryType: database.getInjuryTypes()){
			 //System.out.println(database.getInjuryTypeID(injuryType) + "\t"+ injuryType);
		 }
		
	}
}
